# Generated by Django 5.2 on 2025-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
