# Generated by Django 5.2 on 2025-04-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_position_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='deptName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
