# Generated by Django 5.2 on 2025-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_depart_deptname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
